CREATE TABLE IF NOT EXISTS `Orders` (
  `Id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Description` VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
